[package]
name = "perm_test"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "perm_test"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
rand = "0.9.0"
